-- WAOTD DETAILS OF THE EMP ALONG WITH
-- ANNUAL SALARY IF THEY ARE WORKING IN DEPT 30 AS SALESMAN AND THEIR ANNUAL SALARY HAS TO BE GREATER THAN 14000.

select emp.*, sal*12 as annualsal 
from emp
where job ='SALESMAN'
and (sal*12) >14000
and deptno =30;