-- .WAQTD NAMES OF EMPLOYEES ALONG WITH
-- ANNUAL SALARY FOR THE EMPLOYEES WORKING
-- AS MANAGER OR CLERK INTO DEPT 10 OR 30
SELECT ename, sal * 12 AS ANNUALSAL
FROM emp
WHERE job IN ('MANAGER', 'CLERK')
AND deptno IN (10, 30);