--  LIST THE EMPLOYEES WHO ARE NOT WORKING AS
-- MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A
-- SALARY IN THE RANGE OF 1000 TO 3000.
select *
from emp
where job not in ('MANAGER','CLERKS')
and deptno in(10,20)
and sal between 1000 AND 3000;